### ISSUE TITLE
`rc` channels fails to upload

### ISSUE THREAD

**Issue by LecrisUT** [conda-forge/spglib-feedstock#93]
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 298, in main
    aserver_api.user(username)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 247, in user
    self._check_response(res)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/__init__.py", line 232, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ('"conda_forge" could not be found', 404)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 154, in main
    binstar_main(command_module, args, _exit,
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/scripts/cli.py", line 136, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.10/site-packages/binstar_client/commands/upload.py", line 302, in main
    raise errors.BinstarError(message) from error
binstar_client.errors.BinstarError: User "conda_forge" does not exist
Failed to upload due to Command '['anaconda', '--quiet', '--show-traceback', '-t', '/tmp/tmpx_zca4ei/binstar.token', 'upload', '/home/conda/feedstock_root/build_artifacts/linux-64/spglib-2.0.2-py38hf1595b5_0.conda', '--user=conda_forge', '--channel=spglib_rc']' returned non-zero exit status 1.. Trying again in 10 seconds
Using BINSTAR_TOKEN for anaconda.org uploads to conda_forge.
INFO:binstar:Using Anaconda API: https://api.anaconda.org
[ERROR] User "conda_forge" does not exist
[ERROR] 
```

**Comment by LecrisUT** [comment]
Oh, god these typos
